<?php
/**
 * @var $this \Cawa\Bootstrap\Components\Collapse
 * @var string $parentId
 * @var string $id
 * @var string $title
 * @var string $titleTag
 * @var string $content
 * @var bool $collapse
 * @var bool $noPanelBody
 */
?>
<div class="panel-heading"
     role="tab"
     id="<?= $id ?>-heanding"
     data-toggle="collapse"
     <?= isset($parentId) ? 'data-parent="#' . $parentId . '"' : '' ?>
     data-target="#<?= $id ?>"
     aria-expanded="<?= $collapse ? 'false' : 'true' ?>"
>
    <<?= $titleTag ?> class="panel-title">
        <?= $title ?>
    </<?= $titleTag ?>>
</div>
<div id="<?= $id ?>"
     class="panel-collapse collapse<?= !$collapse ? ' in' : '' ?>"
     role="tabpanel"
     aria-labelledby="<?= $id ?>-heanding"
>
    <?php if (!$noPanelBody) : ?>
    <div class="panel-body">
    <?php endif; ?>
    <?= $content ?>
    <?php if (!$noPanelBody) : ?>
    </div>
    <?php endif; ?>
</div>
